### ISSUE TITLE
用户save逻辑上有个bug

### ISSUE THREAD

**Issue by peojectwang** [huanzi-qch/base-admin#11]
![image](https://user-images.githubusercontent.com/38562106/95732451-56362380-0cb3-11eb-93ad-eb60d6979056.png)
得排除用户自己本身的问题

**Comment by huanzi-qch** [comment]
> ![image](https://user-images.githubusercontent.com/38562106/95732451-56362380-0cb3-11eb-93ad-eb60d6979056.png)
> 得排除用户自己本身的问题

bug已修复，请更新代码进行测试
