### ISSUE TITLE
Error:(6, 33) java: 程序包org.hibernate.annotations不存在

### ISSUE THREAD

**Issue by q5222890** [huanzi-qch/base-admin#13]
clone下来运行 提示
Error:(6, 33) java: 程序包org.hibernate.annotations不存在

**Comment by huanzi-qch** [comment]
> clone下来运行 提示
> Error:(6, 33) java: 程序包org.hibernate.annotations不存在

请确保网络畅通，重新下载；不行就换一个镜像
