### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by liuchen1393193701** [huanzi-qch/base-admin#15]
CaptchaFilterConfig this class，if you alrealy use PrintWriter,and you not use return keyword,otherwise，console will create error,please look!

**Comment by huanzi-qch** [comment]
> PrintWriter

bug已经修复，请更新代码后进行测试

**Comment by huanzi-qch** [comment]
> CaptchaFilterConfig this class，if you alrealy use PrintWriter,and you not use return keyword,otherwise，console will create error,please look!

bug已经修复，请更新代码后进行测试

**Comment by liuchen1393193701** [comment]
好的，




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huanzi-qch/base-admin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月30日(星期五) 下午5:39
收件人:&nbsp;"huanzi-qch/base-admin"<base-admin@noreply.github.com&gt;;
抄送:&nbsp;"1393193701"<1393193701@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [huanzi-qch/base-admin] bug (#15)





  
CaptchaFilterConfig this class，if you alrealy use PrintWriter,and you not use return keyword,otherwise，console will create error,please look!
  
bug已经修复，请更新代码后进行测试
