### ISSUE TITLE
登录问题！

### ISSUE THREAD

**Issue by stevenXS** [huanzi-qch/base-admin#17]
博主您好，我使用演示的账户登录，一直显示密码错误。

**Comment by huanzi-qch** [comment]
> 博主您好，我使用演示的账户登录，一直显示密码错误。

1、sa/123456，确认没输错吗？
2、确认是不是连错数据库，或者数据库数据是不是有问题。
3、重新down一份最新代码下来，重新导入最新数据库数据。

**Comment by ricky-02** [comment]
@huanzi-qch 谢谢，重写下载后，已经解决该问题。
