### ISSUE TITLE
加解密问题

### ISSUE THREAD

**Issue by 13592423306** [huanzi-qch/base-admin#19]
common.js文件中rsaUtil.encrypt()方法中return rsaUtil.thisKeyPair.encrypt(JSON.stringify(plaintext));  修改为rsaUtil.thisKeyPair.encrypt(plaintext); 则不会造成RSA解密多一个双引号。双引号是因为JSON.stringify()方法造成的。  
请及时修订前后端以及注释，以免给其他同学造成误解。

**Comment by huanzi-qch** [comment]
> common.js文件中rsaUtil.encrypt()方法中return rsaUtil.thisKeyPair.encrypt(JSON.stringify(plaintext)); 修改为rsaUtil.thisKeyPair.encrypt(plaintext); 则不会造成RSA解密多一个双引号。双引号是因为JSON.stringify()方法造成的。
> 请及时修订前后端以及注释，以免给其他同学造成误解。

感谢指出！
前端已经去掉多余的JSON.stringify操作；后端已删除截取去除多余引号的操作；请更新最新代码进行测试
