### ISSUE TITLE
并发多人登录控制在Session超时情况下会误判

### ISSUE THREAD

**Issue by tom-Love-wz** [huanzi-qch/base-admin#2]
首先感谢大佬分享，学到了很多东西！试着跑跑，发现admin用户设置不允许多人登录，然后设置session超时阈值为1分钟，登录系统后静止超过一分钟，刷新页面自动跳到登录页，然后重新登录，会提示不允许多人登录。

请大佬有空看看哦~~

**Comment by huanzi-qch** [comment]
你好，已新增session失效处理，请更新代码进行测试

**Comment by huanzi-qch** [comment]
> 首先感谢大佬分享，学到了很多东西！试着跑跑，发现admin用户设置不允许多人登录，然后设置session超时阈值为1分钟，登录系统后静止超过一分钟，刷新页面自动跳到登录页，然后重新登录，会提示不允许多人登录。
> 
> 请大佬有空看看哦~~

你好，已新增session失效处理，请更新代码进行测试

**Comment by tom-Love-wz** [comment]
已测试，超时的session会在重新请求时被剔除掉。
