### ISSUE TITLE
SqlUtil sql拼接错误

### ISSUE THREAD

**Issue by zhihui1999** [huanzi-qch/base-admin#20]
你好,我在使用SqlUtil拼接sql时
发现当实体类的Integer加入@Like时
在SqlUtil中发现第144行
sql.append(" and ").append(column).append(" = '").append(SqlUtil.escapeSql( (String) fieldValue)).append("'");
中的 (String) fieldValue 
Integer转String错误
我将其改成了String.valueOf(fieldValue)
成功

另外,序列化的实体一般要有serialVersionUID,可以加在忽略拼接的字段
以上
最后感谢开发者的开源

**Comment by huanzi-qch** [comment]
感谢指出！强制转换确实存在较大类转换异常风险，是当时没考虑到使用其他数据类型进行SQL拼接的情况，现在已经改成String.valueOf进行转换，请更新代码进行测试。
