### ISSUE TITLE
很多依赖包没有写到pom文件中?

### ISSUE THREAD

**Issue by xiaoshipricne** [huanzi-qch/base-admin#21]
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.codec.binary.Base64;
import org.aspectj.lang.ProceedingJoinPoint;
import org.aspectj.lang.annotation.Around;
import org.aspectj.lang.annotation.Aspect;
import org.aspectj.lang.annotation.Pointcut;
import org.aspectj.lang.reflect.MethodSignature;
import org.springframework.stereotype.Component;
import org.springframework.web.context.request.RequestContextHolder;
import org.springframework.web.context.request.ServletRequestAttributes;

import javax.servlet.http.HttpServletRequest;

**Comment by huanzi-qch** [comment]
> import com.fasterxml.jackson.databind.DeserializationFeature;
> import com.fasterxml.jackson.databind.ObjectMapper;
> import lombok.extern.slf4j.Slf4j;
> import org.apache.commons.codec.binary.Base64;
> import org.aspectj.lang.ProceedingJoinPoint;
> import org.aspectj.lang.annotation.Around;
> import org.aspectj.lang.annotation.Aspect;
> import org.aspectj.lang.annotation.Pointcut;
> import org.aspectj.lang.reflect.MethodSignature;
> import org.springframework.stereotype.Component;
> import org.springframework.web.context.request.RequestContextHolder;
> import org.springframework.web.context.request.ServletRequestAttributes;
> 
> import javax.servlet.http.HttpServletRequest;

估计是依赖没下完，重新刷新一下maven
