### ISSUE TITLE
打包出来的jar包运行不起来，报无法找到主清单错误

### ISSUE THREAD

**Issue by carryxiong** [huanzi-qch/base-admin#22]
将下面注释掉修改成如下，jar包可以正常了，不知道有啥区别。。。。
        
            
            
            
            
            
            
            

            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>

            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>2.4.3</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-clean-plugin</artifactId>
                <version>3.1.0</version>
            </plugin>

**Comment by carryxiong** [comment]
删除掉这个配置就可以打包运行了
<configuration>-->

**Comment by huanzi-qch** [comment]
> config



> ```
> 将下面注释掉修改成如下，jar包可以正常了，不知道有啥区别。。。。
>     
>         
>         
>         
>         
>         
>         
>         
> 
>         <plugin>
>             <groupId>org.springframework.boot</groupId>
>             <artifactId>spring-boot-maven-plugin</artifactId>
>         </plugin>
> 
>         
>         <plugin>
>             <groupId>org.apache.maven.plugins</groupId>
>             <artifactId>maven-resources-plugin</artifactId>
>             <version>2.4.3</version>
>         </plugin>
>         <plugin>
>             <groupId>org.apache.maven.plugins</groupId>
>             <artifactId>maven-clean-plugin</artifactId>
>             <version>3.1.0</version>
>         </plugin>
> ```



> ```
> 将下面注释掉修改成如下，jar包可以正常了，不知道有啥区别。。。。
>     
>         
>         
>         
>         
>         
>         
>         
> 
>         <plugin>
>             <groupId>org.springframework.boot</groupId>
>             <artifactId>spring-boot-maven-plugin</artifactId>
>         </plugin>
> 
>         
>         <plugin>
>             <groupId>org.apache.maven.plugins</groupId>
>             <artifactId>maven-resources-plugin</artifactId>
>             <version>2.4.3</version>
>         </plugin>
>         <plugin>
>             <groupId>org.apache.maven.plugins</groupId>
>             <artifactId>maven-clean-plugin</artifactId>
>             <version>3.1.0</version>
>         </plugin>
> ```

就加多了自己的config配置啊，jar包文件名、jar包输出位置等，我试过多次都正常，你是不是找对生成的jar包？

**Comment by huanzi-qch** [comment]
可以看下md文档“常见问题”，里面有讲如何正确打包

**Comment by carryxiong** [comment]
我知道了，是在package目录下有个jar包，但是我不知道为啥target目录下也生成了一个jar包，我以为就是那个jar包，然后那个target目录下的jar包无法执行。
