### ISSUE TITLE
您好，大哥，找你太难了

### ISSUE THREAD

**Issue by wuwb521** [huanzi-qch/base-admin#3]
我好不容易用咱的系统，然后单独改了一个多表关联的地方，用的自定义sql，现在又出现了前后台数据交互时候有个加解密，这个是需要我怎么配置呀，要哭了，我整了两天了

**Comment by huanzi-qch** [comment]
> 我好不容易用咱的系统，然后单独改了一个多表关联的地方，用的自定义sql，现在又出现了前后台数据交互时候有个加解密，这个是需要我怎么配置呀，要哭了，我整了两天了

你好，具体是什么问题？加解密操作按说是跟业务操作没关系，如果是因为加解密的关系，可以先看下博客了解我们的加解密流程 https://www.cnblogs.com/huanzi-qch/p/10913636.html
